---
# Set sasl dir
- name: Ensure Direcory for sasl 
  file:
   path: /etc/postfix/sasl
   state: directory
   owner: root
   group: root
   mode: 0755
#  when: postfixsmtp_sasl_auth_enable

# Idee by https://github.com/geerlingguy/ansible-role-postfix/blob/master/tasks/main.yml
# Just for the Base Configuration
# Is easest to manage because you don't have to the j2 file template.
- name: Update Postfix generic configuration.
  lineinfile:
    dest: "{{ postfix_config_file }}"
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} = "
  with_items:
    - name: inet_interfaces
      value: "{{ postfix_inet_interfaces }}"
    - name: inet_protocols
      value: "{{ postfix_inet_protocols }}"
  notify: restart postfix
  when: configure_postfix_type == "generic"

# https://github.com/mrlesmithjr/ansible-postfix/blob/master/tasks/main.yml
- name: Create postfix configuration main.cf via template
  template:
    src: "main.cf.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/main.cf"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: restart postfix
  when: configure_postfix_type == "template"

# Original by https://github.com/mrlesmithjr/ansible-postfix/blob/master/tasks/main.yml
- name: Create canonical maps if enabled
  template:
    src: "hash/canonical.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/canonical"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  notify: handler_postmap_canonical
  when: enable_canonical_maps and configure_postfix_type == "template"

- name: Create postfix configuration 'generic'
  template:
    src: "hash/generic.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/generic"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: handler_postmap_generic
  when: enable_generic_maps and configure_postfix_type == 'template'

- name: Create postfix configuration sasl 'passwd' file
  template:
    src: "sasl/passwd.j2"
    dest: "{{ postfix_sasl_passwdfile }}"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: handler_postmap_sasl_passwd
  when: postfixsmtp_sasl_auth_enable and configure_postfix_type == 'template'

- name: rebuilding access.db
  command: "postmap /etc/postfix/access"
  tags: [postfix]
  notify: 
    - handler_postmap_access
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'

- name: configure /etc/aliases
  template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  notify: postfix-postalias


#- name: rebuilding resieve.db
#  command: "postmap /etc/postfix/resieve"
#  tags: [postfix]
#  notify: restart postfix
#  when: >
#        postfix.changed and
#        postfix_domain_rewrite_filetype == 'hash'

- name: rebuilding generic.db
  command: "postmap /etc/postfix/generic"
  tags: [postfix]
  notify: handler_postmap_generic
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'

- name: rebuilding access.db
  command: "postmap /etc/postfix/access"
  tags: [postfix]
  notify: restart postfix
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'