---
# Set sasl dir
- name: Ensure Direcory for sasl
  file:
   path: /etc/postfix/sasl
   state: directory
   owner: root
   group: root
   mode: 0755
  when: postfixsmtp_sasl_auth_enable

# Set sasl dir
- name: Ensure Direcory for ldap
  file:
   path: /etc/postfix/ldap
   state: directory
   owner: root
   group: root
   mode: 0755
  when:  postfix_mailbox_backend_type == "ldap"

# Set sasl dir
- name: Ensure Direcory for psql
  file:
   path: /etc/postfix/sasl
   state: directory
   owner: root
   group: root
   mode: 0755
  when:  postfix_mailbox_backend_type == "psql"

# Set sasl dir
- name: Ensure Direcory for MySQL Backend
  file:
   path: /etc/postfix/mysql
   state: directory
   owner: root
   group: root
   mode: 0755
#  when: postfix_mailbox_backend_type == "mysql"

# Idee by https://github.com/geerlingguy/ansible-role-postfix/blob/master/tasks/main.yml
# Just for the Base Configuration
# Is easest to manage because you don't have to the j2 file template.
- name: Update Postfix generic configuration.
  lineinfile:
    dest: "{{ postfix_config_file }}"
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} = "
  with_items:
    - name: inet_interfaces
      value: "{{ postfix_inet_interfaces }}"
    - name: inet_protocols
      value: "{{ postfix_inet_protocols }}"
  notify: restart postfix
  when: configure_postfix_type == "generic"

# https://github.com/mrlesmithjr/ansible-postfix/blob/master/tasks/main.yml
- name: Create postfix configuration main.cf via template
  template:
    src: "main.cf.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/main.cf"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: restart postfix
  when: configure_postfix_type == "template"

- name: configure /etc/aliases
  template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    backup: yes
    mode: 0644
  notify: postfix-postalias

# Original by https://github.com/mrlesmithjr/ansible-postfix/blob/master/tasks/main.yml
- name: Create access maps if enabled
  template:
    src: "hash/access.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/access"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  notify: handler_postmap_access
  when: enable_access_maps and configure_postfix_type == "template"

- name: Create canonical maps if enabled
  template:
    src: "hash/canonical.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/canonical"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  notify: handler_postmap_canonical
  when: enable_canonical_maps and configure_postfix_type == "template"

- name: Create postfix configuration 'generic'
  template:
    src: "hash/generic.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/generic"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: handler_postmap_generic
  when: enable_generic_maps and configure_postfix_type == 'template'

- name: Create postfix configuration 'relocated'
  template:
    src: "hash/relocated.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/relocatedc"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: handler_postmap_relocated
  when: enable_relocated_maps and configure_postfix_type == 'template'

- name: Create postfix configuration 'transport'
  template:
    src: "hash/transport.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/transport"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: handler_postmap_transport
  when: enable_transport_maps and configure_postfix_type == 'template'

- name: Create postfix configuration 'transport'
  template:
    src: "hash/virtual.j2"
    dest: "{{ postfix_mail_dir_postfix_config }}/virtual"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: handler_virtual_transport
  when: enable_virtual_maps and configure_postfix_type == 'template'

- name: Create postfix configuration sasl 'passwd' file
  template:
    src: "sasl/passwd.j2"
    dest: "{{ postfix_sasl_passwdfile }}"
    mode: 0644
    owner: "root"
    group: "root"
  tags: [postfix]
  register: postfix
  notify: handler_postmap_sasl_passwd
  when: postfixsmtp_sasl_auth_enable and configure_postfix_type == 'template'

- name: rebuilding access.db
  command: "postmap /etc/postfix/access"
  tags: [postfix]
  notify: restart postfix
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'

- name: rebuilding canonical.db
  command: "postmap /etc/postfix/canonical"
  tags: [postfix]
  notify: handler_postmap_canonical
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'

- name: rebuilding generic.db
  command: "postmap /etc/postfix/generic"
  tags: [postfix]
  notify: handler_postmap_generic
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'

- name: rebuilding relocated.db
  command: "postmap /etc/postfix/relocated"
  tags: [postfix]
  notify: handler_postmap_relocated
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'

- name: rebuilding transport.db
  command: "postmap /etc/postfix/transport"
  tags: [postfix]
  notify: handler_postmap_transport
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'

- name: rebuilding transport.db
  command: "postmap /etc/postfix/virtual"
  tags: [postfix]
  notify: handler_postmap_virtual
  when: >
        postfix.changed and
        postfix_domain_rewrite_filetype == 'hash'

## backends
# ldap
