---
# https://wiki.debian.org/PostfixAndSASL
- name: Upgrade packages
  package: 
    upgrade: yes

- name: Checking to make sure mailutils is installed if Debian os is used.
  apt:
    name:
      - 'mailutils'
    state: "present"
  tags: [postfix]
  when: ansible_os_family == 'Debian'

