---
# https://github.com/mrlesmithjr/ansible-postfix/tree/master/templates
# https://github.com/practical-ansible/mail/blob/master/defaults/main.yml
# https://github.com/mrlesmithjr/ansible-postfix/blob/master/tasks/main.yml
# https://github.com/practical-ansible/mail
# https://github.com/Oefenweb/ansible-postfix
# 
- name: Verify base domain is set
  fail:
    msg: >
      Mail domain must be defined set env variable PRACTICAL_MAIL_DOMAIN
      to your desired domain name
  when: postfix_base_domain is not defined

- name: Ensure postfix is installed.
  package:
    name: postfix
    state: present
  tags: [postfix]

- name: Checking to make sure mailutils is installed if Debian os is used.
  apt:
    name:
      - 'mailutils'
    state: "present"
  tags: [postfix]
  when: ansible_os_family == 'Debian'

- name: Checking to make sure mailx is installed if RedHat not Fedora is used.
  yum:
    name:
      - 'mailx'
    state: "present"
  tags: [postfix]
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora"

- name: Checking to make sure mailx is installed on Fedora
  dnf:
    name:
      - 'mailx'
    state: "present"
  tags: [postfix]
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution == "Fedora"

- name: Ensure postfix is started and enabled at system boot.
  systemd:
     name: postfix
     state: "{{ postfix_service_state }}"
     enabled: "{{ postfix_service_enabled }}"

- name: Include tasks for testmail
  include_tasks: testmail.yml
  when: enable_send_testmail

- name: Include tasks for config-build
  include_tasks: config-build.yml

- name: Include tasks for certificates
  include_tasks: certificates.yml
  when: enable_postfix_certbot