---
# https://github.com/mrlesmithjr/ansible-postfix/tree/master/templates
# https://github.com/robertdebock/ansible-role-postfix/blob/master/tasks/main.yml
# https://github.com/practical-ansible/mail
# https://github.com/Oefenweb/ansible-postfix
# https://wiki.gentoo.org/wiki/Complete_Virtual_Mail_Server/Postfix_to_Database/en
# https://www.df.eu/de/support/df-faq/cloudserver/anleitungen/spam-und-virenschutz-mit-postfix-debian/

- name: Verify base domain is set
  fail:
    msg: >
      Mail domain must be defined set env variable PRACTICAL_MAIL_DOMAIN
      to your desired domain name
  when: postfix_base_domain is not defined

- include_vars: "{{ ansible_os_family }}.yml"
- include_tasks: "{{ ansible_os_family }}.yml"

- name: Ensure postfix is installed.
  package:
    name: postfix
    state: present
  tags: postfix

- name: Ensure postfix is started and enabled
  service:
    name: postfix
    state: "started"
    enabled: "true"

- name: create group
  group:
    name: "{{ postfix_group }}"
    state: present

- name: Update Postfix configuration.
  lineinfile:
    dest: "{{ postfix_config_file }}"
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} ="
  with_items:
    - name: inet_interfaces
      value: "{{ postfix_inet_interfaces }}"
    - name: inet_protocols
      value: "{{ postfix_inet_protocols }}"
  notify: restart postfix

- name: Include tasks for testmail
  include_tasks: testmail.yml
  when: enable_send_testmail

- name: Include tasks for config-build
  include_tasks: config-build.yml

- name: Include tasks for certificates
  include_tasks: certificates.yml
  when: enable_postfix_certbot

- name: Include tasks for IMAP Server Dovecot
  include_tasks: dovecot.yml
  when: enable_postfix_dovecot

- name: Include tasks for saslauthd
  include_tasks: saslauthd.yml
  when: enable_postfix_saslauthd
