---
- name: Checking to make sure mailx is installed if RedHat not Fedora is used.
  yum:
    name:
      - 'mailx'
    state: "present"
  tags: [postfix]
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora"

- name: Checking to make sure mailx is installed on Fedora
  dnf:
    name:
      - 'mailx'
    state: "present"
  tags: [postfix]
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution == "Fedora"

- name: Install Postfix dependencies
  yum:
    name:
      - cyrus_sasl
      - cyrus_sasl-gs2
      - cyrus-sasl-plain
      - cyrus-sasl-md5
      - cyrus-sasl-ldap
      - cyrus-sasl-gssapi
      - cyrus-sasl-ntlm
      - cyrus-sasl-sql
    state: present
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora"
        postfix_smtp_sasl_auth_enable