---
- name: restart postfix
  service:
    name: "postfix"
    state: "restarted"
  when: not ansible_check_mode

- name: reload postfix
  service:
    name: "postfix"
    state: "reloaded"
  when: not ansible_check_mode

- name: handler_postmap_canonical
  command: postmap {{ postfix_mail_dir_postfix_config }}/canonical

- name: handler_postmap_generic
  command: postmap {{ postfix_mail_dir_postfix_config }}/generic

- name: handler_postmap_access
  command: postmap {{ postfix_mail_dir_postfix_config }}/access

- name: handler_postmap_canonical
  command: postmap {{ postfix_mail_dir_postfix_config }}/canonical

- name: handler_postmap_resieve
  command: postmap {{ postfix_mail_dir_postfix_config }}/resieve

- name: handler_postmap_sasl_passwd
  command: postmap "{{ postfix_sasl_passwdfile }}"

- name: postfix-postalias
  command: postalias /etc/aliases