---
- name: restart postfix
  service:
    name: "postfix"
    state: "restarted"
  when: not ansible_check_mode

- name: reload postfix
  service:
    name: "postfix"
    state: "reloaded"
  when: not ansible_check_mode

- name: start postmap
  command: postmap {{postmapfile}}