---
- name: restart postfix
  service:
    name: "postfix"
    state: "restarted"
  when: not ansible_check_mode

- name: reload postfix
  service:
    name: "postfix"
    state: "reloaded"
  when: not ansible_check_mode

- name: postfix-postalias
  command: postalias /etc/aliases

- name: handler_postmap_access
  command: postmap {{ postfix_mail_dir_postfix_config }}/access

- name: handler_postmap_canonical
  command: postmap {{ postfix_mail_dir_postfix_config }}/canonical

- name: handler_postmap_generic
  command: postmap {{ postfix_mail_dir_postfix_config }}/generic

- name: handler_postmap_relocated
  command: postmap {{ postfix_mail_dir_postfix_config }}/relocated

- name: handler_postmap_transport
  command: postmap {{ postfix_mail_dir_postfix_config }}/transport

- name: handler_postmap_virtual
  command: postmap {{ postfix_mail_dir_postfix_config }}/virtual

- name: handler_postmap_sasl_passwd
  command: postmap "{{ postfix_sasl_passwdfile }}"

- name: handler_dovecot_restart
  systemd: 
    name: dovecot
    state: "restarted"

- name: handler_saslauthd
  systemd: 
    name: saslauthd
    state: "restarted"

